export const SMSH_TICKET_ROOT = "SMSH_TICKET_ROOT"
export const SMSH_TICKET_HOME = "SMSH_TICKET_HOME"
export const SMSH_TICKET_DETAILS = "SMSH_TICKET_DETAILS"
export const SMSH_TICKET_CHECKOUT = "SMSH_TICKET_CHECKOUT"